[package]
name = "strappier-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["json", "macros"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.47.1", features = ["full"] }
