name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile check
        run: cargo check --verbose
      - name: Run tests
        run: cargo test --verbose

  build:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: strappier-service
          path: target/release/strappier-service

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: strappier-service
          path: .
      - name: Copy binary to VPS
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.OVH_VPS_PROD_HOST }}
          username: ${{ secrets.OVH_VPS_PROD_USER }}
          key: ${{ secrets.OVH_VPS_PROD_DEPLOY_SSH_KEY }}
          port: ${{ secrets.OVH_VPS_PROD_PORT }}
          source: "strappier-service"
          target: "/home/deployer/strappier-service/bin/"
